version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns: [ "*" ]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
