# This workflow will build a middleman project with bundle

name: Build and Publish

on:
  push:
    branches:
      - master
      # Push events to branches matching refs/heads/release-*
      - 'release-*'

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  RUN_EXTERNAL_CHECKS: true

jobs:
  complete_build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          bundler-cache: true # would run bundle install
      - name: Set up NodeJS
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Run the build
        run: bundle exec rake complete_build
  push_to_gh_pages:
    needs: complete_build
    runs-on: ubuntu-latest
    env:
      GITHUB_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
      - name: Set up NodeJS
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Set up user in git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Set up upstream and publish to gh pages
        run: |
          git remote add upstream 'https://github-actions:${GITHUB_PASSWORD}@github.com/gocd/docs.go.cd'
          bundle install
          bundle exec rake publish
        env:
          REMOTE_NAME: "upstream"
          ALLOW_DIRTY: true
  sync_to_s3:
    needs: push_to_gh_pages
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: "${{ secrets.S3_BUCKET }}"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          bundler-cache: true # would run bundle install
      - name: Set up NodeJS
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          aws-region: "${{ secrets.AWS_REGION }}"
      - name: Upload to S3
        run: bundle exec rake upload_to_s3
