# This workflow will build a middleman project with bundle

name: Testing For PRs

on: [ pull_request ]

env:
  RUN_EXTERNAL_CHECKS: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # would run bundle install
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Run the build
        run: bundle exec rake complete_build
